[package]
name = "ast-build"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.23"
tree-sitter-rust = "0.23"

# Other dependencies...
# Make sure none of these are directly requiring tree-sitter > 0.20.9